# -*- coding: utf-8 -*-
"""Home work 05.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6tYq1zpOGLxI_d9OJk2GUTo49mBwaXh
"""

amount = int(input("Enter sale price: "))
if(amount>0):
    if amount >=100:
        dis = amount*0.10
    elif amount <100:
        dis = amount*0.05
    print("Discount :",dis)
    print("Net pay : ",amount-dis)
else:
    print("invalid amount")
